"""empty message

Revision ID: 3cd55e70d2dc
Revises: 43b501e6a576
Create Date: 2021-05-04 16:29:22.538225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd55e70d2dc'
down_revision = '43b501e6a576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree', sa.Column('projectID', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tree', 'projectID')
    # ### end Alembic commands ###
