"""added iw, integrated DP and iw with DS

Revision ID: 41e753068777
Revises: 50c940bce223
Create Date: 2021-03-27 18:15:46.275380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41e753068777'
down_revision = '50c940bce223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interactswith',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fromDsID', sa.Integer(), nullable=True),
    sa.Column('toDsID', sa.Integer(), nullable=True),
    sa.Column('iwType', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['fromDsID'], ['designsolution.id'], name='fk_iwOut_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['toDsID'], ['designsolution.id'], name='fk_iwIn_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('designparameter', sa.Column('dsID', sa.Integer(), nullable=True))
    op.drop_constraint('fk_dp_id', 'designparameter', type_='foreignkey')
    op.create_foreign_key('fk_dp_id', 'designparameter', 'designsolution', ['dsID'], ['id'], ondelete='CASCADE')
    op.drop_column('designparameter', 'ds')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('designparameter', sa.Column('ds', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_dp_id', 'designparameter', type_='foreignkey')
    op.create_foreign_key('fk_dp_id', 'designparameter', 'designsolution', ['ds'], ['id'], ondelete='CASCADE')
    op.drop_column('designparameter', 'dsID')
    op.drop_table('interactswith')
    # ### end Alembic commands ###
