"""empty message

Revision ID: 43b501e6a576
Revises: 41e753068777
Create Date: 2021-04-22 14:29:42.719318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43b501e6a576'
down_revision = '41e753068777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interactswith', sa.Column('treeID', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_iw_id', 'interactswith', 'tree', ['treeID'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_iw_id', 'interactswith', type_='foreignkey')
    op.drop_column('interactswith', 'treeID')
    # ### end Alembic commands ###
