"""added DP

Revision ID: 50c940bce223
Revises: 
Create Date: 2021-03-27 18:02:47.009413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c940bce223'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designparameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('value', sa.String(length=200), nullable=True),
    sa.Column('unit', sa.String(length=200), nullable=True),
    sa.Column('treeID', sa.Integer(), nullable=True),
    sa.Column('ds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ds'], ['designsolution.id'], name='fk_dp_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treeID'], ['tree.id'], name='fk_dp_tree', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('designparameter')
    # ### end Alembic commands ###
